#!/bin/bash

parse_yaml() {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}


file_name=`basename $1 .md`
eval $(parse_yaml $1 "")

if [ -e "$_pdmk_template" ]; then
  pandoc $_pdmk_arg -o $file_name.$_pdmk_output $1 --template=$_pdmk_template
else
  pandoc $_pdmk_arg -o $file_name.$_pdmk_output $1 --template=$HOME/.pdmk/template/$_pdmk_template
fi
